import { z } from "zod";

export const CurrencySchema = z.union([
  z.literal("AED"), // United Arab Emirates Dirham
  z.literal("AFN"), // Afghan Afghani
  z.literal("ALL"), // Albanian Lek
  z.literal("AMD"), // Armenian Dram
  z.literal("ANG"), // Netherlands Antillean Guilder
  z.literal("AOA"), // Angolan Kwanza
  z.literal("ARS"), // Argentine Peso
  z.literal("AUD"), // Australian Dollar
  z.literal("AWG"), // Aruban Florin
  z.literal("AZN"), // Azerbaijani Manat
  z.literal("BAM"), // Bosnia-Herzegovina Convertible Mark
  z.literal("BBD"), // Barbadian Dollar
  z.literal("BDT"), // Bangladeshi Taka
  z.literal("BGN"),
  z.literal("BHD"),
  z.literal("BIF"),
  z.literal("BMD"),
  z.literal("BND"),
  z.literal("BOB"),
  z.literal("BRL"),
  z.literal("BSD"),
  z.literal("BTN"),
  z.literal("BWP"),
  z.literal("BYN"),
  z.literal("BZD"),
  z.literal("CAD"),
  z.literal("CDF"),
  z.literal("CHF"),
  z.literal("CLP"),
  z.literal("CNY"),
  z.literal("COP"),
  z.literal("CRC"),
  z.literal("CVE"),
  z.literal("CZK"),
  z.literal("DJF"),
  z.literal("DKK"),
  z.literal("DOP"),
  z.literal("DZD"),
  z.literal("EGP"),
  z.literal("ERN"),
  z.literal("ETB"),
  z.literal("EUR"),
  z.literal("FJD"),
  z.literal("FKP"),
  z.literal("GBP"),
  z.literal("GEL"),
  z.literal("GHS"),
  z.literal("GIP"),
  z.literal("GMD"),
  z.literal("GNF"),
  z.literal("GTQ"),
  z.literal("GYD"),
  z.literal("HKD"),
  z.literal("HNL"),
  z.literal("HRK"),
  z.literal("HTG"),
  z.literal("HUF"),
  z.literal("IDR"),
  z.literal("ILS"),
  z.literal("INR"),
  z.literal("IQD"),
  z.literal("IRR"),
  z.literal("ISK"),
  z.literal("JEP"),
  z.literal("JMD"),
  z.literal("JOD"),
  z.literal("JPY"),
  z.literal("KES"),
  z.literal("KGS"),
  z.literal("KHR"),
  z.literal("KID"),
  z.literal("KMF"),
  z.literal("KRW"),
  z.literal("KWD"),
  z.literal("KYD"),
  z.literal("KZT"),
  z.literal("LAK"),
  z.literal("LBP"),
  z.literal("LKR"),
  z.literal("LRD"),
  z.literal("LSL"),
  z.literal("LTL"),
  z.literal("LVL"),
  z.literal("LYD"),
  z.literal("MAD"),
  z.literal("MDL"),
  z.literal("MGA"),
  z.literal("MKD"),
  z.literal("MMK"),
  z.literal("MNT"),
  z.literal("MOP"),
  z.literal("MRU"),
  z.literal("MUR"),
  z.literal("MVR"),
  z.literal("MWK"),
  z.literal("MXN"),
  z.literal("MYR"),
  z.literal("MZN"),
  z.literal("NAD"),
  z.literal("NGN"),
  z.literal("NIO"),
  z.literal("NOK"),
  z.literal("NPR"),
  z.literal("NZD"),
  z.literal("OMR"),
  z.literal("PAB"),
  z.literal("PEN"),
  z.literal("PGK"),
  z.literal("PHP"),
  z.literal("PKR"),
  z.literal("PLN"),
  z.literal("PYG"),
  z.literal("QAR"),
  z.literal("RON"),
  z.literal("RSD"),
  z.literal("RUB"),
  z.literal("RWF"),
  z.literal("SAR"),
  z.literal("SBD"),
  z.literal("SCR"),
  z.literal("SDG"),
  z.literal("SEK"),
  z.literal("SGD"),
  z.literal("SHP"),
  z.literal("SLL"),
  z.literal("SOS"),
  z.literal("SRD"),
  z.literal("SSP"),
  z.literal("STN"),
  z.literal("SYP"),
  z.literal("SZL"),
  z.literal("THB"),
  z.literal("TJS"),
  z.literal("TMT"),
  z.literal("TND"),
  z.literal("TOP"),
  z.literal("TRY"),
  z.literal("TTD"),
  z.literal("TWD"),
  z.literal("TZS"),
  z.literal("UAH"),
  z.literal("UGX"),
  z.literal("USD"),
  z.literal("UYU"),
  z.literal("UZS"),
  z.literal("VED"),
  z.literal("VES"),
  z.literal("VND"),
  z.literal("VUV"),
  z.literal("WST"),
  z.literal("XAF"),
  z.literal("XCD"),
  z.literal("XOF"),
  z.literal("XPF"),
  z.literal("XXX"),
  z.literal("YER"),
  z.literal("ZAR"),
  z.literal("ZMW"),
]);
